name: Adguard dns and block rules
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        shell: bash

      - name: Git push to release
        run: |
                git init
                git config --local user.name "github-actions[bot]"
                git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
                git checkout -b rules
                git add .
                git commit
                git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
                git push -f origin rules
